global:
  scrape_interval: 10s

scrape_configs:
  - job_name: Linux-host
#    scrape_interval: 10s
    static_configs:
     - targets:
        - 10.10.10.13:9100
        - 10.10.10.55:9100
        - 10.10.10.10:9100
        - 10.10.10.12:9100
#        - 10.10.10.44:9100

  - job_name: win-server
    static_configs:
     - targets:
        - 10.10.10.44:9182

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 10.10.10.32:9093


#  - job_name: Mikrotik
#    static_configs:
#      - targets:
#         - 10.10.10.1 # mikrotik ip
#    metric_path: /snmp
#    params:
#       module: [mikrotik]
#    relabel_configs:
#         - source_labels: [__address__]
#           target_label: __param_target
#         - source_labels: [__param_target]
#           target_label: instance
#         - target_label: __address__
#           replacement: 10.10.10.31:9090 # server ip

